#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    enable_vimfiler_gitstatus = true
    filemanager = "defx"
    filetree_direction = "left"
    default_indent = 2
    expand_tab = true
    project_rooter_patterns = ['.git/']
    wildignore = '*/node_modules/*'
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"
[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30
[[layers]]
name = "lang#typescript"
[[layers]]
  name = "git"
  git_plugin = 'gina'
[[layers]]
  name = "denite"
[[layers]]
  name = "VersionControl"
[[layers]]
  name = "debug"
  debugger_plugin = "vimspector"
[[layers]]
  name = "github"
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "lang#javascript"
[[layers]]
  name = "lang#python"
  enabled_linters = ['flake8']
[[layers]]
  name = "colorscheme"
[[layers]]
  name = "fzf"
[[layers]]
  name = "test"
[[layers]]
  name = "checkers"
[[layers]]
  name = "lang#sh"
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "lang#rust"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rls"]
[[layers]]
  name = "lsp"
