#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "dark"
    guifont = "SauceCodePro Nerd Font Mono:h14"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "nil"
    buffer_index_type = 4
    windows_index_type = 3
    windows_leader = ","
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    filemanager = "defx"
    filetree_direction = "left"
    default_indent = 2
    expand_tab = true
    project_rooter_patterns = ['.git/', 'package.json']
    project_rooter_outermost = false
    wildignore = "*/node_modules/*,*/coverage/*"
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    automatic_update = true
    lint_engine = "ale"
    disabled_plugins = ["nvim-lspconfig", "cmp-buffer"]
    autocomplete_method = "nvim-cmp"
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "cycle"

[[layers]]
    name = 'core'
    filetree_show_hidden = true
    enable_smooth_scrolling = true
[[layers]]
   name = 'core#statusline'
   enable = false
[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 20
[[layers]]
  name = "git"
  git_plugin = 'fugitive'
[[layers]]
  name = "VersionControl"
[[layers]]
  name = "debug"
  debugger_plugin = "vimspector"
[[layers]]
  name = "github"
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "lang#javascript"
[[layers]]
  name = "lang#python"
  enabled_linters = ['flake8']
[[layers]]
  name = "colorscheme"
[[layers]]
  name = "test"
  [layers.override_config]
    python_runner = 'pytest'
    strategy = "dispatch"
[[layers]]
  name = "checkers"
  lint_on_the_fly = true
  lint_on_save = true
[[layers]]
  name = "format"
  format_on_save = true
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "lang#markdown"
  enabled_formater = ["prettier"]
[[layers]]
  name = "lang#rust"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rls"]
[[layers]]
  name = "telescope"
[[layers]]
  name = "lang#graphql"
[[custom_plugins]]
  repo = "justinmk/vim-sneak"
[[custom_plugins]]
  repo = "nvim-lua/plenary.nvim"
[[custom_plugins]]
  repo = "APZelos/blamer.nvim"
[[custom_plugins]]
  repo = "https://github.com/hrsh7th/nvim-cmp.git"
  merged = 0
[[custom_plugins]]
  name = "voldikss/vim-floaterm"
[[custom_plugins]]
  name = "hashivim/vim-terraform"
[[custom_plugins]]
  name = "juliosueiras/vim-terraform-completion"
[[custom_plugins]]
  name = "vim-syntastic/syntastic"
[[custom_plugins]]
  name = "nvim-treesitter/nvim-treesitter"
  hook_post_update = "TSUpdate"
[[custom_plugins]]
  name = "antoinemadec/FixCursorHold.nvim"
[[custom_plugins]]
  name = "nvim-neotest/neotest"
[[custom_plugins]]
  name = "haydenmeade/neotest-jest"
[[custom_plugins]]
  name = "nvim-neotest/neotest-vim-test"
[[custom_plugins]]
  name = "neovim/nvim-lspconfig"
[[custom_plugins]]
  name = "VonHeikemen/lsp-zero.nvim"
[[custom_plugins]]
  name = "L3MON4D3/LuaSnip"
[[custom_plugins]]
  name = "rafamadriz/friendly-snippets"
[[custom_plugins]]
  name = 'williamboman/nvim-lsp-installer'
[[custom_plugins]]
  name = 'hrsh7th/nvim-cmp'
[[custom_plugins]]
  name = 'hrsh7th/cmp-buffer'
[[custom_plugins]]
  name = 'hrsh7th/cmp-path'
[[custom_plugins]]
  name = 'saadparwaiz1/cmp_luasnip'
[[custom_plugins]]
  name = 'hrsh7th/cmp-nvim-lsp'
[[custom_plugins]]
  name = 'hrsh7th/cmp-nvim-lua'
[[custom_plugins]]
  name = 'rafamadriz/friendly-snippets'
[[custom_plugins]]
  name = 'neovim/nvim-lspconfig'
