#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    windows_leader = ","
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    enable_vimfiler_gitstatus = true
    filemanager = "defx"
    filetree_direction = "left"
    enable_vimfiler_gitstatus = true
    default_indent = 2
    expand_tab = true
    project_rooter_patterns = ['.git/', 'package.json']
    project_rooter_outermost = false
    wildignore = "*/node_modules/*,*/coverage/*"
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    automatic_update = true
    lint_engine = "ale"
    autocomplete_method = "coc"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"
[[layers]]
    name = 'core'
    filetree_show_hidden = true
    enable_smooth_scrolling = true
[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 20
[[layers]]
  name = "lang#typescript"
[[layers]]
  name = "git"
  git_plugin = 'fugitive'
[[layers]]
  name = "VersionControl"
[[layers]]
  name = "debug"
  debugger_plugin = "vimspector"
[[layers]]
  name = "github"
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "lang#javascript"
[[layers]]
  name = "lang#python"
  enabled_linters = ['flake8']
[[layers]]
  name = "colorscheme"
[[layers]]
  name = "test"
  use_ultest = true
  [layers.override_config]
    python_runner = 'pytest'
    strategy = "dispatch"
[[layers]]
  name = "checkers"
  lint_on_the_fly = true
  lint_on_save = true
[[layers]]
  name = "format"
  format_on_save = true
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "lang#markdown"
  enabled_formater = ["prettier"]
[[layers]]
  name = "lang#rust"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rls"]
[[layers]]
  name = "lsp"
  filetypes = [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
  ]
  enabled_clients = ['tsserver']
[[layers]]
  name = "telescope"
[[custom_plugins]]
  repo = "justinmk/vim-sneak"
[[custom_plugins]]
  repo = "TimUntersberger/neogit"
[[custom_plugins]]
  repo = "nvim-lua/plenary.nvim"
[[custom_plugins]]
  repo = "github/copilot.vim"
[[custom_plugins]]
  repo = "APZelos/blamer.nvim"
[[custom_plugins]]
    repo = "https://github.com/hrsh7th/nvim-cmp.git"
    merged = 0
